---
title: "Team Report"
author: "Carlos Godinez"
date: 10/19/2021
output:
  github_document:
    toc: true
---

## Background

In late 2019 a novel coronavirus quickly spread throughout the global population causing a pandemic that is still causing massive disruptions in late 2021. SARS-CoV-2, the virus that causes COVID-19, is a highly contagious respiratory virus. In response to the rapidly spreading disease and it’s even more infectious variants, local governments and counties throughout the pandemic have instituted face covering and mask mandates to slow the spread. While specifics change from location to location,  a mask mandate largely requires individuals to cover their face and noses when in a public setting . The intent behind this is to reduce the viral load that a potentially infectious person could spread to others [1]. Masks have been found to be effective in slowing the spread of COVID-19 and are recommended to be worn by the CDC when in geographical areas of high spread [2]. 

## Dataset Used

For this challenge, we used two datasets provided in the Covid challenge, the population data from the US census  as well as Covid cases and deaths by county overtime taken from a dataset collected by the New York Times . The population data is from the US census and is collected in the form of the American Community Survey (ACS) Total Population by County 5 year estimate. An important note about this data: “Estimates of urban and rural populations, housing units, and characteristics reflect boundaries of urban areas defined based on Census 2010 data. As a result, data for urban and rural areas from the ACS do not necessarily reflect the results of ongoing urbanization.” We did not look into how our results would change if there was a higher population in urban areas, however, it would be interesting to re-do our analysis once the most recent 2020 census data is released and see if there are any significant changes. While the population data is the most accurate data we can obtain currently, it isn’t perfect and is a bit out of date, both of which are limiting factors of this dataset. The COVID-19 data is obtained from the New York times and includes cumulative cases and deaths over time for each county from January 21, 2020 to present.  The dataset obtains the time series data “from state and local governments and health departments in an attempt to provide a complete record of the ongoing outbreak.” The documentation about the table provides an important node about potential limitations: “Since the first reported coronavirus case in Washington State on Jan. 21, 2020, The Times has tracked cases of coronavirus in real time as they were identified after testing. Because of the widespread shortage of testing, however, the data is necessarily limited in the picture it presents of the outbreak.”  We were not concerned about this limitation, as this is a problem every dataset about COVID-19 will encounter since not everyone who has had COVID-19 has received a test for a variety of reasons.

We are using a [CDC database](https://data.cdc.gov/Policy-Surveillance/U-S-State-and-Territorial-Public-Mask-Mandates-Fro/62d6-pm5i) for whether or not a mask mandate was in place by county every day from April 10, 2020 through August 15, 2021. This data “derived from publicly available state and territorial executive orders, administrative orders, resolutions, and proclamations (“orders”) for COVID-19 that expressly require individuals to wear masks in public found by the CDC, COVID-19 Community Intervention & Critical Populations Task Force, Monitoring & Evaluation Team, Mitigation Policy Analysis Unit, Center for State, Tribal, Local, and Territorial Support, Public Health Law Program, and Max Gakh, Assistant Professor, School of Public Health, University of Nevada, Las Vegas.” Two other important notes are “any orders not available through publicly accessible websites are not included in these data” and “These data do not include data on counties that have opted out of their state mask mandate pursuant to state law.” Therefore, for each date, every county either has a “Yes” (there was a mask mandate in place), “No” (there was not a mask mandate in place), or NA (it is unknown whether or not there was a mask mandate in place).  

We identified two main limitations of this data set. The first is the amount of NAs in the dataset, and how to best complete our analysis with the NAs. If the data was not publicly accessible by the entities mentioned above, an NA was placed in the mask mandate column. As a quick check, some members of our team looked at their home counties and saw NAs during times they knew there was a mask mandate in place, such as counties in California. There are other states, such as Florida, where there are only NAs for every county through the entire dataset. While this has limited some of our analysis, after researching, this seems like the best dataset available. It is impossible to have a perfect dataset by county of if there was a mask mandate in place, especially since there is no central government database for which counties report mandates like this. In our analysis, for counties where there was at least one day with a yes/no mask mandate, we treat the NAs as no. This is not perfect, however, we decided it was better to treat NA as no than NA as yes.

The second limitation of the dataset is that a mask mandate does not necessarily equal compliance. We thought about different ways we could take this into account and looked at a dataset of self-reported mask-wearing survey. We decided not to pursue incorporating this dataset into our analysis as it is during only July 2 - July 14 2020, and people’s mask usage and opinions change over time. We did not attempt to minimize this limitation in our analysis, but it is important to keep in mind that mandate does not necessarily equal people wearing masks, or wearing masks correctly. 



## Team Question



## Our Graph




## Conclusion




## Future Exploration 


# Notes

<!-- -------------------------------------------------- -->

[1] https://pubmed.ncbi.nlm.nih.gov/32512240/

[2] https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/cloth-face-cover-guidance.html



